steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/shortener:$COMMIT_SHA",
        "-t",
        "gcr.io/$PROJECT_ID/shortener:latest",
        ".",
      ]
    id: "build"
    waitFor: ["-"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/shortener:$COMMIT_SHA"]
    id: "push"
    waitFor: ["build"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "shortener",
        "--image",
        "gcr.io/$PROJECT_ID/shortener:$COMMIT_SHA",
        "--platform",
        "managed",
        "--region",
        "us-central1",
        "--allow-unauthenticated"
      ]
    id: "deploy"
